#include <gtest/gtest.h>
#include <string>

#define NMD_ASSEMBLY_IMPLEMENTATION
#include "../nmd_assembly.h"

struct TestInstruction
{
	const char* s; // string
	nmd_x86_instruction i; // instruction
};

#define CPUFLAG(x) {!!((x)&(1<<0)),!!((x)&(1<<1)),!!((x)&(1<<2)),!!((x)&(1<<3)),!!((x)&(1<<4)),!!((x)&(1<<5)),!!((x)&(1<<6)),!!((x)&(1<<7)),!!((x)&(1<<8)),!!((x)&(1<<9)),!!((x)&(1<<10)),!!((x)&(1<<11)),!!((x)&(1<<13)),!!((x)&(1<<14)),!!((x)&(1<<15)),!!((x)&(1<<16)),!!((x)&(1<<17)),!!((x)&(1<<18)),!!((x)&(1<<19)),!!((x)&(1<<20)),!!((x)&(1<<21)),!!((x)&(1<<22)),!!((x)&(1<<23)),!!((x)&(1<<24)),!!((x)&(1<<25)),!!((x)&(1<<26)),!!((x)&(1<<27)),!!((x)&(1<<28)),!!((x)&(1<<29)),!!((x)&(1<<30)),!!((x)&(1<<31))}

#define OPERAND(type, size, isImplicit, action, reg, imm, mem) {type,size,isImplicit,action,type==NMD_X86_OPERAND_TYPE_REGISTER?reg:(type==NMD_X86_OPERAND_TYPE_IMMEDIATE?imm:mem)}
#define MEM(segment, base, index, scale, disp) {segment,base,index,scale,disp}

static const TestInstruction instructions[] = {
	/*string            valid  hasModrm hasSIB hasRex opsz64 reprfx   mode             length  opcode  opcodeSize  id                              prefixes                                numPrefixes  numOperands  group                          fullInstruction     operands                                                                                                                           modrm  sib    immMask           dispMask           immediate  displacement  opcodeMap                   encoding                 vex  modifiedFlags                                                                                                testedFlags                                     setFlags    clearedFlags                                    undefinedFlags                                                                                      rex  segmentOverride  simdPrefix */
	{"int3",           {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0xcc,   1,          NMD_X86_INSTRUCTION_INT3,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT,                 {0xcc},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_IF | NMD_X86_EFLAGS_NT | NMD_X86_EFLAGS_VM | NMD_X86_EFLAGS_AC | NMD_X86_EFLAGS_VIF), CPUFLAG(NMD_X86_EFLAGS_NT | NMD_X86_EFLAGS_VM), CPUFLAG(0), CPUFLAG(NMD_X86_EFLAGS_TF | NMD_X86_EFLAGS_RF), CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"int3",           {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0xcc,   1,          NMD_X86_INSTRUCTION_INT3,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT,                 {0xcc},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_IF | NMD_X86_EFLAGS_NT | NMD_X86_EFLAGS_VM | NMD_X86_EFLAGS_AC | NMD_X86_EFLAGS_VIF), CPUFLAG(NMD_X86_EFLAGS_NT | NMD_X86_EFLAGS_VM), CPUFLAG(0), CPUFLAG(NMD_X86_EFLAGS_TF | NMD_X86_EFLAGS_RF), CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"int3",           {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0xcc,   1,          NMD_X86_INSTRUCTION_INT3,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT,                 {0xcc},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_IF | NMD_X86_EFLAGS_NT | NMD_X86_EFLAGS_VM | NMD_X86_EFLAGS_AC | NMD_X86_EFLAGS_VIF), CPUFLAG(NMD_X86_EFLAGS_NT | NMD_X86_EFLAGS_VM), CPUFLAG(0), CPUFLAG(NMD_X86_EFLAGS_TF | NMD_X86_EFLAGS_RF), CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"nop",            {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0x90,   1,          NMD_X86_INSTRUCTION_NOP,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x90},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"nop",            {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x90,   1,          NMD_X86_INSTRUCTION_NOP,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x90},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"nop",            {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x90,   1,          NMD_X86_INSTRUCTION_NOP,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x90},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"ret",            {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0xc3,   1,          NMD_X86_INSTRUCTION_RET,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_RET,                 {0xc3},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"ret",            {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0xc3,   1,          NMD_X86_INSTRUCTION_RET,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_RET,                 {0xc3},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"ret",            {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0xc3,   1,          NMD_X86_INSTRUCTION_RET,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_RET,                 {0xc3},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"pushf",          {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0x9c,   1,          NMD_X86_INSTRUCTION_PUSHF,      NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9c},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"pushf",          {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 2,      0x9c,   1,          NMD_X86_INSTRUCTION_PUSHF,      NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE, 1,           0,           NMD_GROUP_NONE,                {0x66, 0x9c},       {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE }},
	{"pushf",          {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 2,      0x9c,   1,          NMD_X86_INSTRUCTION_PUSHF,      NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE, 1,           0,           NMD_GROUP_NONE,                {0x66, 0x9c},       {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE }},
	{"pushfd",         {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 2,      0x9c,   1,          NMD_X86_INSTRUCTION_PUSHFD,     NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE, 1,           0,           NMD_GROUP_NONE,                {0x66, 0x9c},       {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE }},
	{"pushfd",         {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x9c,   1,          NMD_X86_INSTRUCTION_PUSHFD,     NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9c},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"pushfq",         {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x9c,   1,          NMD_X86_INSTRUCTION_PUSHFQ,     NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9c},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"popf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0x9d,   1,          NMD_X86_INSTRUCTION_POPF,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9d},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"popf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 2,      0x9d,   1,          NMD_X86_INSTRUCTION_POPF,       NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE, 1,           0,           NMD_GROUP_NONE,                {0x66, 0x9d},       {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE }},
	{"popf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 2,      0x9d,   1,          NMD_X86_INSTRUCTION_POPF,       NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE, 1,           0,           NMD_GROUP_NONE,                {0x66, 0x9d},       {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE }},
	{"popfd",          {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 2,      0x9d,   1,          NMD_X86_INSTRUCTION_POPFD,      NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE, 1,           0,           NMD_GROUP_NONE,                {0x66, 0x9d},       {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE }},
	{"popfd",          {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x9d,   1,          NMD_X86_INSTRUCTION_POPFD,      NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9d},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"popfq",          {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x9d,   1,          NMD_X86_INSTRUCTION_POPFQ,      NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9d},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"retf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0xcb,   1,          NMD_X86_INSTRUCTION_RETF,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_RET,                 {0xcb},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"retf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0xcb,   1,          NMD_X86_INSTRUCTION_RETF,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_RET,                 {0xcb},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"retf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0xcb,   1,          NMD_X86_INSTRUCTION_RETF,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_RET,                 {0xcb},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"leave",          {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0xc9,   1,          NMD_X86_INSTRUCTION_LEAVE,      NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0xc9},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"leave",          {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0xc9,   1,          NMD_X86_INSTRUCTION_LEAVE,      NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0xc9},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"leave",          {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0xc9,   1,          NMD_X86_INSTRUCTION_LEAVE,      NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0xc9},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"int1",           {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0xf1,   1,          NMD_X86_INSTRUCTION_INT1,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT,                 {0xf1},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"int1",           {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0xf1,   1,          NMD_X86_INSTRUCTION_INT1,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT,                 {0xf1},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"int1",           {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0xf1,   1,          NMD_X86_INSTRUCTION_INT1,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT,                 {0xf1},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"push es",        {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x06,   1,          NMD_X86_INSTRUCTION_PUSH,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x06},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"push es",        {false, false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x06,   1,          NMD_X86_INSTRUCTION_PUSH,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x06},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"push ss",        {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x16,   1,          NMD_X86_INSTRUCTION_PUSH,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x16},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"push ss",        {false, false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x16,   1,          NMD_X86_INSTRUCTION_PUSH,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x16},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"push ds",        {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x1e,   1,          NMD_X86_INSTRUCTION_PUSH,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x1e},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"push ds",        {false, false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x1e,   1,          NMD_X86_INSTRUCTION_PUSH,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x1e},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"push cs",        {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x0e,   1,          NMD_X86_INSTRUCTION_PUSH,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x0e},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"push cs",        {false, false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x0e,   1,          NMD_X86_INSTRUCTION_PUSH,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x0e},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"pop es",         {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x07,   1,          NMD_X86_INSTRUCTION_POP,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x07},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"pop es",         {false, false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x07,   1,          NMD_X86_INSTRUCTION_POP,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x07},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"pop ds",         {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x1f,   1,          NMD_X86_INSTRUCTION_POP,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x1f},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"pop ds",         {false, false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x1f,   1,          NMD_X86_INSTRUCTION_POP,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x1f},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"daa",            {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x27,   1,          NMD_X86_INSTRUCTION_DAA,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x27},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF | NMD_X86_EFLAGS_SF | NMD_X86_EFLAGS_ZF | NMD_X86_EFLAGS_PF),  CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF), CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(NMD_X86_EFLAGS_OF),                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"daa",            {false, false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x27,   1,          NMD_X86_INSTRUCTION_DAA,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x27},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF | NMD_X86_EFLAGS_SF | NMD_X86_EFLAGS_ZF | NMD_X86_EFLAGS_PF),  CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF), CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(NMD_X86_EFLAGS_OF),                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"aaa",            {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x37,   1,          NMD_X86_INSTRUCTION_AAA,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x37},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF),                                                              CPUFLAG(NMD_X86_EFLAGS_AF),                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(NMD_X86_EFLAGS_OF | NMD_X86_EFLAGS_SF | NMD_X86_EFLAGS_ZF | NMD_X86_EFLAGS_PF),             0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"aaa",            {false, false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x37,   1,          NMD_X86_INSTRUCTION_AAA,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x37},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF),                                                              CPUFLAG(NMD_X86_EFLAGS_AF),                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(NMD_X86_EFLAGS_OF | NMD_X86_EFLAGS_SF | NMD_X86_EFLAGS_ZF | NMD_X86_EFLAGS_PF),             0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"das",            {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x2f,   1,          NMD_X86_INSTRUCTION_DAS,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x2f},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF | NMD_X86_EFLAGS_SF | NMD_X86_EFLAGS_ZF | NMD_X86_EFLAGS_PF),  CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF), CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(NMD_X86_EFLAGS_OF),                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"das",            {false, false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x2f,   1,          NMD_X86_INSTRUCTION_DAS,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x2f},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF | NMD_X86_EFLAGS_SF | NMD_X86_EFLAGS_ZF | NMD_X86_EFLAGS_PF),  CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF), CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(NMD_X86_EFLAGS_OF),                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"aas",            {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x3f,   1,          NMD_X86_INSTRUCTION_AAS,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x3f},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF),                                                              CPUFLAG(NMD_X86_EFLAGS_AF),                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(NMD_X86_EFLAGS_OF | NMD_X86_EFLAGS_SF | NMD_X86_EFLAGS_ZF | NMD_X86_EFLAGS_PF),             0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"aas",            {false, false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x3f,   1,          NMD_X86_INSTRUCTION_AAS,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x3f},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_CF | NMD_X86_EFLAGS_AF),                                                              CPUFLAG(NMD_X86_EFLAGS_AF),                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(NMD_X86_EFLAGS_OF | NMD_X86_EFLAGS_SF | NMD_X86_EFLAGS_ZF | NMD_X86_EFLAGS_PF),             0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"xlat",           {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0xd7,   1,          NMD_X86_INSTRUCTION_XLAT,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0xd7},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"xlat",           {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0xd7,   1,          NMD_X86_INSTRUCTION_XLAT,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0xd7},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"xlat",           {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0xd7,   1,          NMD_X86_INSTRUCTION_XLAT,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0xd7},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"fwait",          {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0x9b,   1,          NMD_X86_INSTRUCTION_FWAIT,      NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9b},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(NMD_X86_FPU_FLAGS_C0 | NMD_X86_FPU_FLAGS_C1 | NMD_X86_FPU_FLAGS_C2 | NMD_X86_FPU_FLAGS_C3), 0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"fwait",          {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x9b,   1,          NMD_X86_INSTRUCTION_FWAIT,      NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9b},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(NMD_X86_FPU_FLAGS_C0 | NMD_X86_FPU_FLAGS_C1 | NMD_X86_FPU_FLAGS_C2 | NMD_X86_FPU_FLAGS_C3), 0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"fwait",          {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x9b,   1,          NMD_X86_INSTRUCTION_FWAIT,      NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9b},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(NMD_X86_FPU_FLAGS_C0 | NMD_X86_FPU_FLAGS_C1 | NMD_X86_FPU_FLAGS_C2 | NMD_X86_FPU_FLAGS_C3), 0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"hlt",            {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0xf4,   1,          NMD_X86_INSTRUCTION_HLT,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_PRIVILEGE,           {0xf4},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"hlt",            {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0xf4,   1,          NMD_X86_INSTRUCTION_HLT,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_PRIVILEGE,           {0xf4},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"hlt",            {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0xf4,   1,          NMD_X86_INSTRUCTION_HLT,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_PRIVILEGE,           {0xf4},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"cmc",            {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0xf5,   1,          NMD_X86_INSTRUCTION_CMC,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0xf5},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_CF),                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"cmc",            {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0xf5,   1,          NMD_X86_INSTRUCTION_CMC,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0xf5},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_CF),                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"cmc",            {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0xf5,   1,          NMD_X86_INSTRUCTION_CMC,        NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0xf5},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_CF),                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"sahf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0x9e,   1,          NMD_X86_INSTRUCTION_SAHF,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9e},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_SF | NMD_X86_EFLAGS_ZF | NMD_X86_EFLAGS_AF | NMD_X86_EFLAGS_PF | NMD_X86_EFLAGS_CF),  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"sahf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x9e,   1,          NMD_X86_INSTRUCTION_SAHF,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9e},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_SF | NMD_X86_EFLAGS_ZF | NMD_X86_EFLAGS_AF | NMD_X86_EFLAGS_PF | NMD_X86_EFLAGS_CF),  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"sahf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x9e,   1,          NMD_X86_INSTRUCTION_SAHF,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9e},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(NMD_X86_EFLAGS_SF | NMD_X86_EFLAGS_ZF | NMD_X86_EFLAGS_AF | NMD_X86_EFLAGS_PF | NMD_X86_EFLAGS_CF),  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"lahf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0x9f,   1,          NMD_X86_INSTRUCTION_LAHF,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9f},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"lahf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0x9f,   1,          NMD_X86_INSTRUCTION_LAHF,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9f},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"lahf",           {true,  false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0x9f,   1,          NMD_X86_INSTRUCTION_LAHF,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_NONE,                {0x9f},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	//{"into",           {true,  false,   false, false, false, false,   NMD_X86_MODE_16, 1,      0xce,   1,          NMD_X86_INSTRUCTION_INTO,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT,                 {0xce},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	//{"into",           {true,  false,   false, false, false, false,   NMD_X86_MODE_32, 1,      0xce,   1,          NMD_X86_INSTRUCTION_INTO,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT,                 {0xce},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	//{"into",           {false, false,   false, false, false, false,   NMD_X86_MODE_64, 1,      0xce,   1,          NMD_X86_INSTRUCTION_INTO,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT,                 {0xce},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"iret",           {true, false,   false, false, false, false,    NMD_X86_MODE_16, 1,      0xcf,   1,          NMD_X86_INSTRUCTION_IRET,       NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT | NMD_GROUP_RET, {0xcf},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE }},
	{"iretd",          {true, false,   false, false, false, false,    NMD_X86_MODE_16, 2,      0xcf,   1,          NMD_X86_INSTRUCTION_IRETD,      NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE, 1,           0,           NMD_GROUP_INT | NMD_GROUP_RET, {0x66,0xcf},        {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE }},
	{"iret",           {true, false,   false, false, false, false,    NMD_X86_MODE_32, 2,      0xcf,   1,          NMD_X86_INSTRUCTION_IRET,       NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE, 1,           0,           NMD_GROUP_INT | NMD_GROUP_RET, {0x66,0xcf},        {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE }},
	{"iret",           {true, false,   false, false, false, false,    NMD_X86_MODE_64, 2,      0xcf,   1,          NMD_X86_INSTRUCTION_IRET,       NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE, 1,           0,           NMD_GROUP_INT | NMD_GROUP_RET, {0x66,0xcf},        {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_OPERAND_SIZE_OVERRIDE }},
	{"iretd",          {true, false,   false, false, false, false,    NMD_X86_MODE_32, 1,      0xcf,   1,          NMD_X86_INSTRUCTION_IRETD,      NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT | NMD_GROUP_RET, {0xcf},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"iretd",          {true, false,   false, false, false, false,    NMD_X86_MODE_64, 1,      0xcf,   1,          NMD_X86_INSTRUCTION_IRETD,      NMD_X86_PREFIXES_NONE,                  0,           0,           NMD_GROUP_INT | NMD_GROUP_RET, {0xcf},             {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0,   0,               NMD_X86_PREFIXES_NONE                  }},
	{"iretq",          {true, false,   false,  true,  true, false,    NMD_X86_MODE_64, 2,      0xcf,   1,          NMD_X86_INSTRUCTION_IRETQ,      NMD_X86_PREFIXES_REX_W,                 1,           0,           NMD_GROUP_INT | NMD_GROUP_RET, {0x48,0xcf},        {0, 0, 0, 0},                                                                                                                      {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                                         0x48,   0,               NMD_X86_PREFIXES_NONE                  }},
																																																					  
	//{"prefetch [eax]", {{true, false, false, false, false, false},   NMD_X86_MODE_32, 3,      0x0d,   1,          NMD_X86_INSTRUCTION_PREFETCH,   NMD_X86_PREFIXES_NONE,                  0,           1,           NMD_GROUP_NONE, {0x0f, 0x0d, 0x00}, {{NMD_X86_OPERAND_TYPE_MEMORY, 1, false, NMD_X86_OPERAND_ACTION_READ,{NMD_X86_REG_DS,NMD_X86_REG_EAX,0,0,0}},0,0,0}, {0},   {0},   NMD_X86_IMM_NONE, NMD_X86_DISP_NONE, 0,         0,            NMD_X86_OPCODE_MAP_DEFAULT, NMD_X86_INSTRUCTION_ENCODING_LEGACY, {0}, CPUFLAG(0),                                                                                                  CPUFLAG(0),                                     CPUFLAG(0), CPUFLAG(0),                                     CPUFLAG(0),                                                                             0,   0,               NMD_X86_PREFIXES_NONE                  } }
};

TEST(AssemblerAndDisassemblerTest, TestAllInstructions)
{	
	nmd_x86_instruction instruction;
	char formattedInstruction[128];
	uint8_t buffer[NMD_X86_MAXIMUM_INSTRUCTION_LENGTH];

	// Test all instructions in the array above.
	for (size_t i = 0; i < _NMD_NUM_ELEMENTS(instructions); i++)
	{
		SCOPED_TRACE("INDEX:" + std::to_string(i) + '(' + instructions[i].s + ')');

		// Test decoder
		EXPECT_EQ(nmd_x86_decode(&instructions[i].i.buffer, instructions[i].i.length, &instruction, (NMD_X86_MODE)instructions[i].i.mode, NMD_X86_DECODER_FLAGS_ALL), instructions[i].i.valid);
		if (instructions[i].i.valid)
		{
			// Test decoder
			EXPECT_EQ(memcmp(&instructions[i].i, &instruction, sizeof(nmd_x86_instruction)), 0); 
			
			// Test length disassembler
			EXPECT_EQ(nmd_x86_ldisasm(instructions[i].i.buffer, instructions[i].i.length, (NMD_X86_MODE)instructions[i].i.mode), instructions[i].i.length);

			// Test formatter
			nmd_x86_format(&instruction, formattedInstruction, NMD_X86_INVALID_RUNTIME_ADDRESS, NMD_X86_FORMAT_FLAGS_DEFAULT);
			EXPECT_EQ(strcmp(formattedInstruction, instructions[i].s), 0);
			
			// Test assembler
			memset(buffer, 0x00, sizeof(buffer));
			EXPECT_EQ(nmd_x86_assemble(formattedInstruction, buffer, sizeof(buffer), NMD_X86_INVALID_RUNTIME_ADDRESS, (NMD_X86_MODE)instructions[i].i.mode, 0), instructions[i].i.length);
			EXPECT_EQ(memcmp(buffer, instructions[i].i.buffer, sizeof(buffer)), 0);
		}
	}

	//const uint8_t oneByteInstructions[] = {,,,0xce,0xcf,0x98,0x99,0xd6,0xf8,0xf9,0xfa,0xfb,0xfc,0xfd};
	//const uint8_t twoByteInstructions[] = { 0x05,0x06,0x07,0x08,0x09,0x0b,0x0e,0x30,0x31,0x32,0x33,0x34,0x35,0x37,0x77,0xa0,0xa1,0xa2,0xa8,0xa9,0xaa };
}

#define EMULATOR_BLOCK_SIZE (1024 * 1024) /* 1MB */

TEST(EmulatorTest, TestAllInstructions)
{
	nmd_x86_cpu cpu;
	memset(&cpu, 0, sizeof(cpu));
	cpu.mode = NMD_X86_MODE_32;
	cpu.physicalMemory = malloc(EMULATOR_BLOCK_SIZE);
	cpu.physicalMemorySize = EMULATOR_BLOCK_SIZE;
	cpu.virtualAddress = 0x3b000; /* Some random number(address) */
	cpu.rip = cpu.virtualAddress + 0x1000; /* Execution starts 0x1000 bytes after the start of the block */
	cpu.rsp.l64 = cpu.virtualAddress + 0x48000; /* The bottom of the stack is 0x48000 bytes after the start of the block */

	void* mem = NMD_EMULATOR_RESOLVE_VA(cpu.virtualAddress + 0x200);
	*(uint64_t*)mem = 0;

	/* 00 - add Eb, Gb */
	memcpy(NMD_EMULATOR_RESOLVE_VA(cpu.rip), "\x00\x18", 2);
	cpu.rax.l64 = cpu.virtualAddress + 0x200;
	*(uint8_t*)mem = 10;
	cpu.rbx.l8 = 27;
	EXPECT_EQ(nmd_x86_emulate(&cpu, 1), true);
	EXPECT_EQ(*(uint8_t*)mem, 37);

	/* 01 - add Gb, Eb */
	memcpy(NMD_EMULATOR_RESOLVE_VA(cpu.rip), "\x01\x18", 2);
	cpu.rbx.l64 = 1234;
	EXPECT_EQ(nmd_x86_emulate(&cpu, 1), true);
	EXPECT_EQ(*(uint32_t*)mem, 1271);

	/* 02 - add Gv, Ev */
	memcpy(NMD_EMULATOR_RESOLVE_VA(cpu.rip), "\x02\x18", 2);
	cpu.rbx.l8 = 11;
	*(uint64_t*)mem = 100;
	EXPECT_EQ(nmd_x86_emulate(&cpu, 1), true);
	EXPECT_EQ(cpu.rbx.l8, 111);

	/* 03 - add Ev, Gv */
	memcpy(NMD_EMULATOR_RESOLVE_VA(cpu.rip), "\x03\x18", 2);
	cpu.rbx.l32 = 472;
	*(uint64_t*)mem = 1000;
	EXPECT_EQ(nmd_x86_emulate(&cpu, 1), true);
	EXPECT_EQ(cpu.rbx.l64, 1472);

	/* 04 - add al, lb */
	memcpy(NMD_EMULATOR_RESOLVE_VA(cpu.rip), "\x04\x20", 2);
	cpu.rax.l8 = 3;
	EXPECT_EQ(nmd_x86_emulate(&cpu, 1), true);
	EXPECT_EQ(cpu.rax.l8, 35);

	/* 05 - add rAX, lv */
	memcpy(NMD_EMULATOR_RESOLVE_VA(cpu.rip), "\x05\x21\x43\x00\x00", 5);
	cpu.rax.l32 = 0x50000;
	EXPECT_EQ(nmd_x86_emulate(&cpu, 1), true);
	EXPECT_EQ(cpu.rax.l32, 0x54321);
}

int main(int argc, char** argv)
{
	::testing::InitGoogleTest(&argc, argv);
	return RUN_ALL_TESTS();
}